tag: lv_exam
task: lv_exam_latvian_language_3
dataset_path: TildeSIA/Latvian_exams
dataset_name: latvian_language_3
output_type: multiple_choice
training_split: null
validation_split: null
test_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: correct_answer_index
doc_to_choice: options
metric_list:
- metric: acc
  aggregation: mean
  higher_is_better: true
- metric: acc_norm
  aggregation: mean
  higher_is_better: true
metadata:
  version: 0
