tag:
  - multiple_choice
task: neurotechnology_hellaswag_lt
dataset_path: neurotechnology/lt_hellaswag
dataset_name: null
output_type: multiple_choice
training_split: null
validation_split: validation
test_split: null
process_docs: !function utils.process_docs
doc_to_text: "{{activity_label}}"
doc_to_target: "{{label}}"
doc_to_choice: "{{endings}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
