tag: squad_sk_tasks
task: squad_sk_2_em
dataset_path: TUKE-DeutscheTelekom/skquad
dataset_name: null
output_type: generate_until
training_split: train
validation_split: validation
test_split: null
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
generation_kwargs:
  until: ["\n\n\n\n"]
  do_sample: false
  temperature: 0
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0