task: c_xnli_hr
dataset_path: jjelinska/COPA_HR
dataset_name: COPA_HR
output_type: multiple_choice
test_split: test
validation_split: validation
training_split: null
doc_to_text: !function utils.doc_to_text
doc_to_target: label
doc_to_choice: !function utils.doc_to_choice
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0