tag: include
task: include_Finnish
dataset_path: CohereLabs/include-base-44
dataset_name: Finnish
output_type: multiple_choice
training_split: null
validation_split: validation
test_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
doc_to_choice: !function utils.doc_to_choice
metric_list:
- metric: acc
  aggregation: mean
  higher_is_better: true
- metric: acc_norm
  aggregation: mean
  higher_is_better: true
metadata:
  version: 0
