tag:
  - anli_czech
task: anli_cs
dataset_path: ctu-aic/anli_cs
dataset_name: null
output_type: generate_until
training_split: train
validation_split: validation
test_split: test
doc_to_text: !function utils.get_prompt
doc_to_target: label
doc_to_choice:
  - "Ne"
  - "Nevím"
  - "Ano"
should_decontaminate: true
doc_to_decontamination_query: evidence
generation_kwargs:
  until: "\n"
  max_gen_toks: 32
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
    regexes_to_ignore:
      - " "
      - "\n"
      - "Odpověď"
      - "[,;.!?:'\"_-]"
  - metric: f1
    aggregation: !function utils.macro_f1_score
    higher_is_better: true
metadata:
  version: 1.0