task: arc_easy_cs
dataset_path: CIIRC-NLP/arc-cs
dataset_name: ARC-Easy
output_type: generate_until
training_split: train
validation_split: validation
test_split: test
doc_to_text: !function utils.get_prompt
doc_to_target: !function utils.doc_to_target
generation_kwargs:
  until: "\n"
  max_gen_toks: 32
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
    regexes_to_ignore:
      - " "
      - "\n"
      - "Odpověď"
      - "[,;.!:'?\"_-]"
metadata:
  version: 1.0