task: copa_hr
dataset_path: classla/copa_hr
dataset_name: default
output_type: multiple_choice
test_split: test
validation_split: validation
training_split: train
doc_to_text: !function utils.doc_to_text_id
doc_to_target: label
doc_to_choice: !function utils.doc_to_choice
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0