tag:
  - truthfulqa
task: neurotechnology_truthfulqa_mc_lt
dataset_path: neurotechnology/lt_thruthful_qa
dataset_name: multiple_choice
output_type: multiple_choice
training_split: null
validation_split: validation
test_split: null
num_fewshot: 0
doc_to_text: "{{ question }}"
doc_to_choice: "{{ mc1_targets.choices }}"
doc_to_target: "{{ mc1_targets.labels.index(1) }}"

should_decontaminate: True
doc_to_decontamination_query: question
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 2.0
