tag:
  - truthfulqa_lt
task: neurotechnology_truthfulqa_mc2_lt
dataset_path: neurotechnology/lt_thruthful_qa
dataset_name: multiple_choice
output_type: multiple_choice
training_split: null
validation_split: validation
test_split: null
num_fewshot: 0
doc_to_text: "{{ question }}"
doc_to_target: 0
doc_to_choice: "{{mc2_targets.choices}}"
process_results: !function utils.process_results_mc2
should_decontaminate: True
doc_to_decontamination_query: question

metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true


metadata:
  version: 2.0
