task: ctkfacts_cs
dataset_path: ctu-aic/ctkfacts_nli
dataset_name: default
output_type: generate_until
test_split: test
training_split: train
validation_split: validation
doc_to_text: !function utils.doc_to_text
doc_to_target: label
doc_to_choice: ["Ne", "Nevím", "Ano"]
generation_kwargs:
  until: "\n"
  max_gen_toks: 32
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
    regexes_to_ignore:
      - " "
      - "\n"
      - "Odpověď"
      - "[,;.!?:'\"_-]"
  - metric: f1
    aggregation: !function utils.macro_f1_score
    higher_is_better: true
metadata:
  version: 1.0